language: php

php:
  - 8.0
  - 7.4
  - 7.3
  - 7.2
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: 8.0
      env: PHPUNIT_VERSION="9"
    - php: 7.4
      env: PHPUNIT_VERSION=""
    - php: 7.3
      env: PHPUNIT_VERSION=""
    - php: 7.2
      env: PHPUNIT_VERSION=""
    - php: 7.1
      env: PHPUNIT_VERSION=""

services:
  - mysql

install:
  - |
      # Install PHPUnit v9 on PHP 8
      if [ "${PHPUNIT_VERSION}" == "9" ]; then
          travis_retry composer require --no-interaction --prefer-dist --dev --ignore-platform-reqs "phpunit/phpunit" 9.*
      # Enable test on PHP 7.1+
      else
          travis_retry composer install --no-interaction --prefer-dist
      fi

script:
  - composer run-script phpunit
  - composer run-script phpstan
